export const POSTS_GET_REQUEST="POSTS_GET_REQUEST";
export const POSTS_GET_FAILURE="POSTS_GET_FAILURE";
export const POSTS_GET_SUCCESS="POSTS_GET_SUCCESS";


export const USER_POSTS_GET_REQUEST="USER_POSTS_GET_REQUEST";
export const USER_POSTS_GET_FAILURE="USER_POSTS_GET_FAILURE";
export const USER_POSTS_GET_SUCCESS="USER_POSTS_GET_SUCCESS";


export const USER_POSTS_ADD_REQUEST="USER_POSTS_ADD_REQUEST";
export const USER_POSTS_ADD_FAILURE="USER_POSTS_ADD_FAILURE";
export const USER_POSTS_ADD_SUCCESS="USER_POSTS_ADD_SUCCESS";

export const USER_POSTS_UPDATE_REQUEST="USER_POSTS_UPDATE_REQUEST";
export const USER_POSTS_UPDATE_FAILURE="USER_POSTS_NEW_FAILURE";
export const USER_POSTS_UPDATE_SUCCESS="USER_POSTS_UPDATE_SUCCESS";


export const USER_POSTS_DELETE_REQUEST="USER_POSTS_DELETE_REQUEST";
export const USER_POSTS_DELETE_FAILURE="USER_POSTS_DELETE_FAILURE";
export const USER_POSTS_DELETE_SUCCESS="USER_POSTS_DELETE_SUCCESS";


